language: python
python:
- '2.7'
sudo: false
env:
- DB=sqlite
- DB=mysql
before_script:
- sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'CREATE DATABASE social_test;'; fi"
- sh -c "if [ '$DB' = 'mysql' ]; then cp .travis/local_settings.py social/local_settings.py;
  fi"
- sh -c "if [ '$DB' = 'mysql' ]; then pip install MySQL-python; fi"
- pip install robotframework robotframework-Selenium2Library
- npm install -g phantomjs
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
install:
- pip install -r requirements.txt
script:
- python manage.py migrate --noinput
- python manage.py runserver &
- pybot test
deploy:
- provider: script
  script: ".travis/deploy.sh"
  on:
    branch: master
    condition: "$DB = mysql"
notifications:
  slack:
    secure: dtio+mN4+R2irXkwLuq8Z+40G6uJG9FMZAi5GniUKu3ShQzwuAICcWX4WMCProlZzBSLOznd+R01kvwfqV3Kl8NzHI6dLOFTG6Yo1pJRM7aC67/E/DZZpsVIYqPaO481KOM2QSrYiu3t7gJy1yIY3BnP73Zz9HX8M4KR2GFxZOe+d9LkFzGMBrNdQp2SXbkrqUubw9SnGv1b9Lx7Jl3cV8dx3u84Y9nGz8r3ykpMHG4oKzf5bQl5Ba8iwGzpn+HxJEzTHTlIIIP4fWft37IDFB+7okfwlbbmgeq9lN/uI1jTQWq3StOdahJj9l99s1FmQlXHKgu2Y5oNIlNPFR+5dEUklXLRYEQi5FjsJDzl5cUz8vS7S/9lHJ1BiXc2qr1lP2qwSqbQMLC2pVwamqyVGBcyU//ei+L/N1QN1oCOdVkvymm0qKiouo3KVMjmdEe22Ty9Sj8Jdyu6so2Uxfy/JCbVNNZTY4Z9OWIfS+CZZPU4TaYp5sTPHawSWBIttoiqf3c+h/w5sKT9+ZFWBdMthYe1kBOLc0elCLSvC57g8dEMPvd1YpBffKSQU9WJrGO7lsPqLSEnPbOUrV/V+Xo2NC948BLLnE8Kd0uFgQ3rEZK08RJN3oiuzQ2BHGOHU9AOyTLPM5O0xRjCwk3QlOdOS3Ya4w4vNBwWhLJHJr15v8k=
