language: python
python:
- '2.7'
sudo: false
env:
- DB=sqlite
- DB=mysql
before_script:
- sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'CREATE DATABASE social_test;'; fi"
- sh -c "if [ '$DB' = 'mysql' ]; then cp .travis/local_settings.py social/local_settings.py; fi"
install:
- pip install -r requirements.txt
- sh -c "if [ '$DB' = 'mysql' ]; then pip install MySQL-python; fi"
script:
- python manage.py migrate --noinput
deploy:
- provider: script
  script: .travis/deploy.sh
  on:
  	branch: master
  	condition: "$DB = mysql"
