language: python
python:
- '2.7'
sudo: false
env:
- DB=sqlite
- DB=mysql
before_script:
- sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'CREATE DATABASE social_test;'; fi"
- sh -c "if [ '$DB' = 'mysql' ]; then cp .travis/local_settings.py social/local_settings.py; fi"
install:
- pip install -r requirements.txt
- sh -c "if [ '$DB' = 'mysql' ]; then pip install MySQL-python; fi"
script:
- python manage.py migrate --noinput
after_success:
- openssl aes-256-cbc -K $encrypted_aa5263036386_key -iv $encrypted_aa5263036386_iv
  -in .travis/ssh_key.enc -out .travis/deploy -d
- echo "madoka.whs.in.th,103.246.18.42 ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDN717hGRfIpN9psGG9q8VXuyVE6w8H1Fa0BqkHOBGJFgAq2uV0/bdYNOpvG27ngLDOmOmNLpdlIYQiI56E+qUPUBxLH3fvhVQVKItP5MRlc97an98Ozg+bOl3SjdUWgFeHIRHwu6UllZUL8U6pjJS/GZsumzwwwTOnLRutYWegxeHjW2DU5Q2BkCU5z/3b+7gFu4s9gRFZ57En/GG2aZYrKBGgoUvjEAOL3B+/nCm1ZTlV2IdKA9gpF/7SyZIozKHXXUA/Xw27aOxebFL2VHO7YtgvkNoiJ5uc6ZQuRB9VPmNKBSYH5fwSICtSHTGlCKLOUd91SBG8JRm/fXES24jn"
  > $HOME/.ssh/known_hosts
- chmod 600 .travis/deploy $HOME/.ssh/known_hosts
- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && ssh -i
  .travis/deploy vu2003@madoka.whs.in.th social/deploy.sh